### ISSUE TITLE
HTTPError: Response code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by kpripper** [zehfernandes/get-vercel-source-code#10]
node index.js aws-kpripper.vercel.app
✔ Getting deployment id
✖ Loading source files tree
HTTPError: Response code 500 (Internal Server Error)    at Request.<anonymous> (file:///D:/Code/get-vercel-source-code-main/node_modules/got/dist/source/as-promise/index.js:86:42)       at Object.onceWrapper (node:events:628:26)    at Request.emit (node:events:525:35)
    at Request._onResponseBase (file:///D:/Code/get-vercel-source-code-main/node_modules/got/dist/source/core/index.js:710:22)    
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///D:/Code/get-vercel-source-code-main/node_modules/got/dist/source/core/index.js:749:13)

**Comment by zehfernandes** [comment]
Hey @kpripper you need to use your VERCEL DEPLOYMENT URL:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1891339/229153746-9844b8eb-0b55-4e40-89b5-71eff35cec9d.png">

**Comment by kpripper** [comment]
> Hey @kpripper you need to use your VERCEL DEPLOYMENT URL:
> 
> <img alt="image" width="445" src="https://user-images.githubusercontent.com/1891339/229153746-9844b8eb-0b55-4e40-89b5-71eff35cec9d.png">

Do you think I didn't understand that I should use my url? To clarify: I used my url.

**Comment by Jobians** [comment]
I'm getting same error

**Comment by deliriant** [comment]
@kpripper a domain is not the same thing as a deployment url.

**Comment by zehfernandes** [comment]
Fixed!
