### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mister-loop** [zehfernandes/get-vercel-source-code#11]
I am getting **500: Internal Server Error** on the `v6/deployments/:id/files` path. 
The `v13/deployments/:url` path is correctly working and extracting the id as well. But somehow this one is not working.

I am doubtful if the endpoint has not changed.

**Comment by zehfernandes** [comment]
I think you are right!

**Comment by Jobians** [comment]
I'm getting same

**Comment by rdwz** [comment]
> I am getting **500: Internal Server Error** on the `v6/deployments/:id/files` path. The `v13/deployments/:url` path is correctly working and extracting the id as well. But somehow this one is not working.
> 
> I am doubtful if the endpoint has not changed.

It changed to v7 response is now base64 encoded:
https://vercel.com/docs/rest-api/endpoints#get-deployment-file-contents

I have a forked version, that gets your source downloaded and decoded, but doesn't work for binary files:
https://github.com/rdwz/vercel-source-fetcher/issues/9

**Comment by zehfernandes** [comment]
Fixed!
