### ISSUE TITLE
Incomplete downloading of files

### ISSUE THREAD

**Issue by Athar-Naveed** [zehfernandes/get-vercel-source-code#13]
hi there, I have tried to download my project with different ways as suggested and guided in issues but, still I am facing the problem. The project is not getting downloaded, your source code is just creating empty directories. If you can help with that. 
Here are the screenshots attached with every possible method mentioned:
![Screenshot 2023-12-21 174550](https://github.com/zehfernandes/get-vercel-source-code/assets/94740625/2de12bcc-8953-456e-b7c7-c16f04e70531)
![Screenshot 2023-12-21 174642](https://github.com/zehfernandes/get-vercel-source-code/assets/94740625/3714f990-f14b-4426-84c4-4b7915ae4e4e)
![Screenshot 2023-12-21 174718](https://github.com/zehfernandes/get-vercel-source-code/assets/94740625/2e5f9fb7-0c6c-4d86-90cc-fad72d94e3dd)

Also, please add relevant comments in your code, for the contributors to understand your code better.

**Comment by zehfernandes** [comment]
I pushed a new version. Can you try again and let me know if it's working?

**Comment by Athar-Naveed** [comment]
Thank You! It works now.
