### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by isyuricunha** [zehfernandes/get-vercel-source-code#7]
Hi,

After install (`npm i`), I try to use the command to download, but I received a error: module not found.

![Error](https://user-images.githubusercontent.com/115634315/197387985-1b208504-ad6b-4ce0-9494-540a7b1fa0c0.png)

Kind regards,
Yuri.

**Comment by isyuricunha** [comment]
Oh, I put the `npm` and `node` versions in the print.

**Comment by MrAmericanMike** [comment]
> Oh, I put the `npm` and `node` versions in the print.

It's `index.js` no `index.html`
